name: "my hello world action"

description: "say hello with GH Actions"

inputs:
  first-greeting:
    description: "who would you like to greet in the console"
    required: true
    default: "Hubot"
  
  second-greeting:
    description: "another person to greet"
    required: true
    default: "Mona the Octocat"
  
  third-greeting:
    description: "a third greeting"
    required: false

runs:
  using: "node12"
  main: "main.js"