# This is a basic workflow to help you get started with Actions

name: JS Actions

# Controls when the action will run. 
on:
  pull_request:
    types: [labeled]
  # Triggers the workflow on push or pull request events but only for the main branch

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  action:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v1
      
      - name: hello-action
        uses: ./.github/actions/hello-world
      
      - name: ha-ha
        uses: ./.github/actions/joke-action

      - name: create-issue
        uses: ./.github/actions/issue-maker
        with:
          repo-token: ${{secrets.GITHUB_TOKEN}}
          joke: ${{steps.jokes.outputs.joke-output}}